
package uk.ac.ucl.chem.ccs.AHECore.API.Rest.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Tue Apr 14 15:23:54 BST 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "stopServer", namespace = "http://Rest.API.AHECore.ccs.chem.ucl.ac.uk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stopServer", namespace = "http://Rest.API.AHECore.ccs.chem.ucl.ac.uk/")

public class StopServer {


}

